include ../../etc/makefile.inc

PKG_NAME = libgds
PKG_DEPS = libutil

UTIL_HEAD = header.h
UTIL_INCS = gdsdata.h gdsutil.h gdsfilter.h
UTIL_OBJS = gdsdata.o gdsutil.o gdsfilter.o

include ../../etc/makefile.lib
